drop policy "Enable read access for all users" on "public"."metro_nums";

revoke delete on table "public"."metro_nums" from "anon";

revoke insert on table "public"."metro_nums" from "anon";

revoke references on table "public"."metro_nums" from "anon";

revoke select on table "public"."metro_nums" from "anon";

revoke trigger on table "public"."metro_nums" from "anon";

revoke truncate on table "public"."metro_nums" from "anon";

revoke update on table "public"."metro_nums" from "anon";

revoke delete on table "public"."metro_nums" from "authenticated";

revoke insert on table "public"."metro_nums" from "authenticated";

revoke references on table "public"."metro_nums" from "authenticated";

revoke select on table "public"."metro_nums" from "authenticated";

revoke trigger on table "public"."metro_nums" from "authenticated";

revoke truncate on table "public"."metro_nums" from "authenticated";

revoke update on table "public"."metro_nums" from "authenticated";

revoke delete on table "public"."metro_nums" from "service_role";

revoke insert on table "public"."metro_nums" from "service_role";

revoke references on table "public"."metro_nums" from "service_role";

revoke select on table "public"."metro_nums" from "service_role";

revoke trigger on table "public"."metro_nums" from "service_role";

revoke truncate on table "public"."metro_nums" from "service_role";

revoke update on table "public"."metro_nums" from "service_role";

alter table "public"."metro_nums" drop constraint "metro_nums_census_year_id_fkey";

alter table "public"."metro_nums" drop constraint "metro_nums_metro_id_fkey";

alter table "public"."metro_nums" drop constraint "metro_num_pkey";

drop index if exists "public"."metro_num_pkey";

drop table "public"."metro_nums";

create table "public"."metro_year_info" (
    "id" bigint generated by default as identity not null,
    "census_year_id" bigint,
    "metro_id" bigint,
    "num" smallint
);


alter table "public"."metro_year_info" enable row level security;

CREATE UNIQUE INDEX metro_num_pkey ON public.metro_year_info USING btree (id);

alter table "public"."metro_year_info" add constraint "metro_num_pkey" PRIMARY KEY using index "metro_num_pkey";

alter table "public"."metro_year_info" add constraint "metro_year_info_census_year_id_fkey" FOREIGN KEY (census_year_id) REFERENCES census_years(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."metro_year_info" validate constraint "metro_year_info_census_year_id_fkey";

alter table "public"."metro_year_info" add constraint "metro_year_info_metro_id_fkey" FOREIGN KEY (metro_id) REFERENCES metros(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."metro_year_info" validate constraint "metro_year_info_metro_id_fkey";

grant delete on table "public"."metro_year_info" to "anon";

grant insert on table "public"."metro_year_info" to "anon";

grant references on table "public"."metro_year_info" to "anon";

grant select on table "public"."metro_year_info" to "anon";

grant trigger on table "public"."metro_year_info" to "anon";

grant truncate on table "public"."metro_year_info" to "anon";

grant update on table "public"."metro_year_info" to "anon";

grant delete on table "public"."metro_year_info" to "authenticated";

grant insert on table "public"."metro_year_info" to "authenticated";

grant references on table "public"."metro_year_info" to "authenticated";

grant select on table "public"."metro_year_info" to "authenticated";

grant trigger on table "public"."metro_year_info" to "authenticated";

grant truncate on table "public"."metro_year_info" to "authenticated";

grant update on table "public"."metro_year_info" to "authenticated";

grant delete on table "public"."metro_year_info" to "service_role";

grant insert on table "public"."metro_year_info" to "service_role";

grant references on table "public"."metro_year_info" to "service_role";

grant select on table "public"."metro_year_info" to "service_role";

grant trigger on table "public"."metro_year_info" to "service_role";

grant truncate on table "public"."metro_year_info" to "service_role";

grant update on table "public"."metro_year_info" to "service_role";

create policy "Enable read access for all users"
on "public"."metro_year_info"
as permissive
for select
to public
using (true);



