create extension if not exists "postgis" with schema "extensions";


create table "public"."census_years" (
    "id" bigint generated by default as identity not null,
    "year" smallint not null,
    "ancestry_ed_url" text,
    "familysearch_ed_url" text
);


alter table "public"."census_years" enable row level security;

create table "public"."districts" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "metro_id" bigint,
    "census_year_id" bigint,
    "geom" geography(MultiPolygon,4326) not null
);


alter table "public"."districts" enable row level security;

create table "public"."metros" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "state" text
);


alter table "public"."metros" enable row level security;

create table "public"."roads" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "geom" geography(LineString,4326) not null,
    "metro_id" bigint,
    "as_of_year" smallint
);


alter table "public"."roads" enable row level security;

CREATE UNIQUE INDEX census_years_pkey ON public.census_years USING btree (id);

CREATE UNIQUE INDEX census_years_year_key ON public.census_years USING btree (year);

CREATE UNIQUE INDEX districts_pkey ON public.districts USING btree (id);

CREATE UNIQUE INDEX metros_pkey ON public.metros USING btree (id);

CREATE UNIQUE INDEX roads_pkey ON public.roads USING btree (id);

CREATE UNIQUE INDEX unique_name_state ON public.metros USING btree (name, state);

alter table "public"."census_years" add constraint "census_years_pkey" PRIMARY KEY using index "census_years_pkey";

alter table "public"."districts" add constraint "districts_pkey" PRIMARY KEY using index "districts_pkey";

alter table "public"."metros" add constraint "metros_pkey" PRIMARY KEY using index "metros_pkey";

alter table "public"."roads" add constraint "roads_pkey" PRIMARY KEY using index "roads_pkey";

alter table "public"."census_years" add constraint "census_years_year_key" UNIQUE using index "census_years_year_key";

alter table "public"."districts" add constraint "districts_census_year_id_fkey" FOREIGN KEY (census_year_id) REFERENCES census_years(id) not valid;

alter table "public"."districts" validate constraint "districts_census_year_id_fkey";

alter table "public"."districts" add constraint "districts_metro_id_fkey" FOREIGN KEY (metro_id) REFERENCES metros(id) not valid;

alter table "public"."districts" validate constraint "districts_metro_id_fkey";

alter table "public"."metros" add constraint "unique_name_state" UNIQUE using index "unique_name_state";

alter table "public"."roads" add constraint "roads_metro_id_fkey" FOREIGN KEY (metro_id) REFERENCES metros(id) not valid;

alter table "public"."roads" validate constraint "roads_metro_id_fkey";

grant delete on table "public"."census_years" to "anon";

grant insert on table "public"."census_years" to "anon";

grant references on table "public"."census_years" to "anon";

grant select on table "public"."census_years" to "anon";

grant trigger on table "public"."census_years" to "anon";

grant truncate on table "public"."census_years" to "anon";

grant update on table "public"."census_years" to "anon";

grant delete on table "public"."census_years" to "authenticated";

grant insert on table "public"."census_years" to "authenticated";

grant references on table "public"."census_years" to "authenticated";

grant select on table "public"."census_years" to "authenticated";

grant trigger on table "public"."census_years" to "authenticated";

grant truncate on table "public"."census_years" to "authenticated";

grant update on table "public"."census_years" to "authenticated";

grant delete on table "public"."census_years" to "service_role";

grant insert on table "public"."census_years" to "service_role";

grant references on table "public"."census_years" to "service_role";

grant select on table "public"."census_years" to "service_role";

grant trigger on table "public"."census_years" to "service_role";

grant truncate on table "public"."census_years" to "service_role";

grant update on table "public"."census_years" to "service_role";

grant delete on table "public"."districts" to "anon";

grant insert on table "public"."districts" to "anon";

grant references on table "public"."districts" to "anon";

grant select on table "public"."districts" to "anon";

grant trigger on table "public"."districts" to "anon";

grant truncate on table "public"."districts" to "anon";

grant update on table "public"."districts" to "anon";

grant delete on table "public"."districts" to "authenticated";

grant insert on table "public"."districts" to "authenticated";

grant references on table "public"."districts" to "authenticated";

grant select on table "public"."districts" to "authenticated";

grant trigger on table "public"."districts" to "authenticated";

grant truncate on table "public"."districts" to "authenticated";

grant update on table "public"."districts" to "authenticated";

grant delete on table "public"."districts" to "service_role";

grant insert on table "public"."districts" to "service_role";

grant references on table "public"."districts" to "service_role";

grant select on table "public"."districts" to "service_role";

grant trigger on table "public"."districts" to "service_role";

grant truncate on table "public"."districts" to "service_role";

grant update on table "public"."districts" to "service_role";

grant delete on table "public"."metros" to "anon";

grant insert on table "public"."metros" to "anon";

grant references on table "public"."metros" to "anon";

grant select on table "public"."metros" to "anon";

grant trigger on table "public"."metros" to "anon";

grant truncate on table "public"."metros" to "anon";

grant update on table "public"."metros" to "anon";

grant delete on table "public"."metros" to "authenticated";

grant insert on table "public"."metros" to "authenticated";

grant references on table "public"."metros" to "authenticated";

grant select on table "public"."metros" to "authenticated";

grant trigger on table "public"."metros" to "authenticated";

grant truncate on table "public"."metros" to "authenticated";

grant update on table "public"."metros" to "authenticated";

grant delete on table "public"."metros" to "service_role";

grant insert on table "public"."metros" to "service_role";

grant references on table "public"."metros" to "service_role";

grant select on table "public"."metros" to "service_role";

grant trigger on table "public"."metros" to "service_role";

grant truncate on table "public"."metros" to "service_role";

grant update on table "public"."metros" to "service_role";

grant delete on table "public"."roads" to "anon";

grant insert on table "public"."roads" to "anon";

grant references on table "public"."roads" to "anon";

grant select on table "public"."roads" to "anon";

grant trigger on table "public"."roads" to "anon";

grant truncate on table "public"."roads" to "anon";

grant update on table "public"."roads" to "anon";

grant delete on table "public"."roads" to "authenticated";

grant insert on table "public"."roads" to "authenticated";

grant references on table "public"."roads" to "authenticated";

grant select on table "public"."roads" to "authenticated";

grant trigger on table "public"."roads" to "authenticated";

grant truncate on table "public"."roads" to "authenticated";

grant update on table "public"."roads" to "authenticated";

grant delete on table "public"."roads" to "service_role";

grant insert on table "public"."roads" to "service_role";

grant references on table "public"."roads" to "service_role";

grant select on table "public"."roads" to "service_role";

grant trigger on table "public"."roads" to "service_role";

grant truncate on table "public"."roads" to "service_role";

grant update on table "public"."roads" to "service_role";

create policy "Enable read access for all users"
on "public"."census_years"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."districts"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."roads"
as permissive
for select
to public
using (true);



